modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/SewingKit/issues"

[[mods]]
    modId="sewingkit"
    version="${file.jarVersion}"
    displayName="Sewing Kit"
    logoFile="logo.png"
    credits="Image used in the mod logo taken by Marco Vech, licensed under CC BY 2.0 "
    authors="gigaherz"
    displayURL="https://github.com/gigaherz/SewingKit"
    description='''
Sewing Kit is a base mod for anything that wants to add sewing features, such as leatherworking or tailoring.
'''

[[dependencies.sewingkit]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.8-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sewingkit]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sewingkit]]
    modId="jei"
    type="optional"
    versionRange="[11.0,)"
    ordering="NONE"
    side="BOTH"
